broccolijs/broccoli-funnel

- index.js
Now that https://github.com/broccolijs/broccoli/pull/197 has landed we can use async rimraf which has better retry semantics on windows. Hoping this can random ember-cli cleanup failures: https://github.com/ember-cli/ember-cli/issues/3044
> use async rimraf

- index.js
- tests/index.js
* `fs.existsSync(somePath)` returns false if `somePath` is a broken symlink (because it is using `fs.stat` and following symlinks).
* The prior cleanup code attempted to avoid unneeded cleanup when the output dir didn't already exist, but this checking actually
hit the issue mentioned above when the input tree's output path has changed (causing the prior symlink to be pointing to an invalid
location).
* Added a test for this issue, and a number of tests confirming that rebuilds work in general (it was previously untested).
> Ensure that cleanup works when output dir is a broken symlink.

- index.js
- tests/index.js
They might be external variables used by other code. This tripped me up for a little while, because I was re-using a filter array variable in other code and it was unexpectedly not an array of strings anymore (it was mutated into an array of objects).
> Don’t mutate any filter arrays passed in.

- CHANGELOG.md
- index.js
I was just trying to update the [example in the Broccoli README](https://github.com/broccolijs/broccoli#using-plugins-in-a-brocfilejs) to use funnel instead of static-compiler, and I noticed that broccoli-funnel doesn't support `new`-less instantiation. Before I put `new Funnel` on the Broccoli README (which is a bit different from how most plugins are instantiated), I figured I'd just ask, is there a reason why you don't like the newless style?
I'm attaching a PR in case you want to allow it.
I goes well with a verbey invocation style as well, using `funnel` as in "to funnel":
```js
var funnel = require('funnel');
var newTree = funnel('foo', ...);
```
> Why no optional `new`?

- index.js
- package.json
This is using the new [broccoli-read-compat](https://github.com/broccolijs/broccoli-read-compat) package to make it possible for individual plugins to use the new syntax, while still supporting older non-`rebuild` aware Broccoli versions.
> Make compatible with legacy broccoli versions.

- index.js
If we have a big input tree and only need to pick explicitly defined files,
it should not be necessary to walk the entire input tree. Instead, take the
property and use that as the complete list of input files.
I didn't include any tests since only internal implementation has changed
and it's not clear how could I mock out the walkSync function to verify that
it wasn't called.
> perf: don't walk the input tree if all files are explicitly defined

- README.md
I think it might confuse people?
> Remove reference to deprecated static-compiler plugin

- index.js
- package.json
- tests/index.js
I want to deprecate regexp, since globs are easier to optimize. Thoughts @rwjblue ?
> when includes are matchable, use them while walking.

- index.js
- tests/index.js
NOTE: this implementation falls back a non matching walk when this occurs. In many cases this is fine, but in some it can be a perf issue.
To help pin-point potential issues you can run with:
running with: `DEBUG=broccoli-* <program> ` can often help identify issues
Future work may include some auto-warnings when a sub-optimal scenario occurs
> [fixes #32] support mixed glob + RegExp includes

- index.js
- package.json
- tests/index.js
Allows the `files` option to be a function that is run every build.
This enables dynamic filtering of files (in an exact, performant way). Also, it  enables `files` to be set lazily/late, helpful in the situation where you don’t yet have the list of files at Brocfile definition time (need some of the build to have finished, an async fetch to run, etc).
Context: https://github.com/broccolijs/broccoli-funnel/issues/25
ps: Adds an early error to prevent usage of both `files` and `include`/`exclude`. That is a slightly backwards incompatible change, but prevents unexpected behavior (because `include`/`exclude` filters are currently never checked if `files` is set).
> Dynamic files filtering via function

- index.js
this ensures the glob is passed through, skipping pruning deps that can't possibly match
> [PERF] walk-sync has a slightly different API

- package.json
> Bump heimdalljs

- package.json
- tests/index.js
Closes #81. Stemming from the adoption of `exists-sync`.
Will track upstream fix at https://github.com/ember-cli/exists-sync/issues/4.
> Update exists-sync. Add relative path test.

- index.js
- package.json
Upcoming changes to broccoli itself will expose this as configuration. broccoli-funnel does not utilize the provided cache directory, so this just tells broccoli to avoid the extraneous work.
> Instruct the builder that we don't need a cache dir.

- package.json
We dropped support for `node@0.12`.
cc @rwjblue @stefanpenner
> Major version bump :tada:

- CHANGELOG.md
I was trying to figure out what warranted a major version bump and decided to jot down what I found by looking at commits in the changelog. 😀 
The only thing I'm not sure about is mentioning #8 in the changelog for 2.0.1, since that issue is still open…
> Update changelog for recent releases

- README.md
A plain string is not allowed - single strings must still be wrapped in an array.
> Fix exclude option docs

- index.js
- tests/index.js
Note that this implementation is a bit of a mess at this point. I'm happy to try to do some follow-on refactoring, but this solves the actual bug noted in #105 and identified while trying to fix aexmachina/ember-cli-sass#204.
Fixes #105.
> Handle empty input nodes when `include` or `exclude` are set.

- .eslintrc.js
- .travis.yml
- appveyor.yml
- index.js
- package.json
- tests/index.js
- yarn.lock
1. only LTS node is supported.
2. Node 8, 10, 12 is added
> Drop support for Node 4, 6, 7, and 9

- index.js
- package.json
- yarn.lock
This is not complete migration as we are missing operations like
1. `removeSync` is from `fs-extra`, `fs.rmdir` has `recursive:true` option, but node 12 onwards. 
2. `unlinkSync` needs to be added to `broccoli-output-wrapper` https://github.com/SparshithNR/broccoli-output-wrapper#apis 
3. `symlinkOrCopy` is one more method that is used extensively. Do we want to support that as well?
> Migrating to input/output facade

- index.js
> Perhaps exists should just check both access and stat on Windows...
Code tries to do as mentioned in the [comment](https://github.com/nodejs/node/issues/30538#issuecomment-555661342) and the fix provided into nodeJS https://github.com/nodejs/node/commit/366a45be2a084f943cee38602eef821ad4a94286
> Fixing windows test with a temporary workaround

- index.js
- tests/index.js
1. Let lookupDestinationPath handle the destDir and getDestinationPath
2. added test case
Addressing #122
> lookupDestinationPath will handle relative path

- index.js
- tests/index.js
> support srcDir with leading slash

- tests/index.js
This PR aims to improve an existing test to actually test file generation when destDir is supplied, as the test name indicates: "is responsible for generating files in the destDir".
> Fix test to actually check generated files with destDir

- index.js
- tests/index.js
PR https://github.com/broccolijs/broccoli-funnel/pull/120 broke the case when you have both `srcDir` and some filtering options like `exclude`. The included test demonstrates the bug. It crashes during `processFile` because the `sourcePath` doesn't exist.
This PR fixes the bug by restoring the correct relative paths as inputs to `walkSync`.
> fix srcDir + filtering

- index.js
- package.json
This "trick" is no longer needed, we can just use `Object.create(null)` instead.
> Remove blank-object dependency.

- index.js
- tests/index.js
Subclassing broccoli-funnel has become somewhat common (e.g. Embroider and ember-css-modules both do it). This adds a basic test to confirm that it generally works.
Additionally, this adds the ability for the subclass to add additional nodes to be considered as part of the broccoli tree graph. This ensures that if you happen to subclass and need to read from another tree to know where to write, you can add that other tree to your inputs and be *guaranteed* that they will have been built before you are called.  Without this change, it _might_ seem to work **sometimes** but it is absolutely not guaranteed to work.
> Allow subclasses to add additional input nodes.

- index.js
- tests/index.js
In a7ed4fa82a6492728cd48cbe3fb0b48c79d4c3ae we added support for passing additional trees to the constructor (to ensure that they can be ready to read in subclasses), but we didn't ensure that all internal usage of `this.input` was limited to the first tree passed. This didn't matter much for the simple symlink srcDir <-> destDir situation, but as soon as you use custom `include`/`exclude` globs (and we therefore have to walk all the files) we would trigger errors.
This fixes that oversight by ensuring that all usage of `this.input` is scoped to `this.input.at(0)`, and adds a previously failing test.
> Ensure adding additional trees does not affect include/exclude results.
